version: 2
jobs:
  BuildAndTest:
    docker:
      - image: circleci/python:3.7
      - image: redis
      - image: circleci/mysql:8.0.4
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - run:
          name: Run Tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox && tox
      - store_artifacts:
          path: htmlcov/
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
            - ".tox"

workflows:
  version: 2
  UpdateCheck:
    jobs:
      - BuildAndTest

